/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b09188ffb08f63599b3e8ec8862e487d)
interface __BaseEnv_Env {
	SANITY_API: "2023-05-03";
	SANITY_DATABASE: "production";
	SANITY_PROJECT: "lqn1inyo";
	SANITY_STUDIO_URL: "https://studio.lisergia.dev";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SANITY_API" | "SANITY_DATABASE" | "SANITY_PROJECT" | "SANITY_STUDIO_URL">> {}
}
